name: trending
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.0.0
  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  google_sign_in: ^5.0.4
  intl_phone_field: ^2.0.0
  otp_text_field: ^1.1.1
  pin_code_fields: ^7.2.0
  provider: ^5.0.0
  cloud_firestore: ^1.0.1
  firebase_storage: ^8.1.3
  image_picker: ^0.8.0+3
  avatar_view: ^1.0.0+4
  youtube_player_flutter: ^8.0.0
  video_player: ^2.1.6
  location: ^4.2.0
  geocoder: ^0.2.1
  http: ^0.13.0
  html: ^0.14.0+3
  gbk2utf8: ^1.0.0
  video_trimmer: ^0.5.1
  cached_network_image: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - rss/logo.png
    - rss/otp.gif
    - rss/profile.png
